name: Lint & Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    strategy:
      matrix:
        go-version: [1.18, 1.19]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest #{{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run Unit Tests
        run: go test ./test -v -cover -coverpkg=./...

  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  coverage:
    name: Show Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Build Coverage Profile
        run: go test ./test -v -race -coverpkg=./... -coverprofile=coverage.txt
      - name: Display Code Coverage
        uses: codecov/codecov-action@v2
        with:
          file: coverage.txt
          flags: unittests
          verbose: true
          fail_ci_if_error: false
