name: Lint & Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Run Unit Tests
        run: go test ./test -v -cover -coverpkg=./...

  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Run Linter
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: latest
          install-go: false

  coverage:
    name: Show Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Build Coverage Profile
        run: go test ./test -v -race -coverpkg=./... -coverprofile=coverage.txt
      - name: Display Code Coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.txt
          flags: unittests
          verbose: true
          fail_ci_if_error: false
